package no.uio.ifi.in2000.team46.data.local.database.entities

import androidx.room.Entity
import androidx.room.PrimaryKey

// favoritelocation represents a saved location in the database, either a single point or an area
// it stores name, type, coordinates, optional metadata like notes and target fish types, and creation timestamp

@Entity(tableName = "favorite_location")
data class FavoriteLocation(
    @PrimaryKey(autoGenerate = true) val id: Int = 0, // autogenerated primary key
    val name: String, // name of the favorite location
    val locationType: String, // either "område" (area) or "punkt" (point)
    val latitude: Double, // center latitude (for area or point)
    val longitude: Double, // center longitude (for area or point)
    val areaPoints: String? = null, // optional json or string representation of polygon points
    val notes: String? = null, // optional user notes for the location
    val targetFishTypes: String? = null, // optional comma-separated fish types
    val createdAt : Long = System.currentTimeMillis() // timestamp when the location was saved
)
